### ISSUE TITLE
Creative a bootable SE card

### ISSUE THREAD

**Issue by smintman** [vonmillhausen/sf2000#1]
Hi sorry to raise an issue as I don’t have any issue with your project. Thanks for the analysis it’s very useful. I have not of a question? 
I was just wondering if you know if it’s possible to set up new SD card with the updated image available online? I’ve tried writing this image to and SD card but it won’t boot it, only the one that came with the console?

**Comment by vonmillhausen** [comment]
@smintman Howdy! This isn't really the place to ask for general help with the SF2000. Your best option would be to join the Retro Handhelds Discord server (https://discord.com/invite/retrohandhelds), and ask in the `Other Devices > data_frog_SF2000` channel 👍
