### ISSUE TITLE
Updates will delete savegames / savestates

### ISSUE THREAD

**Issue by uli42** [vonmillhausen/sf2000#10]
Judging from the update video that data frog released it looks like the whol SD card is overwritten by the update. This fact should be mentioned in the firmware section, maybe with an instruction how to keep the savegames.

**Comment by vonmillhausen** [comment]
Hi @uli42! You're right - I'll add a note about it in my next update, and thanks for the feedback! 👍

**Comment by EricGoldsteinNz** [comment]
You can use tadpole to create a backup of all your save games before reimaging, or alternatively just use tadpole to update and you’ll retain all your saves and ROMs.

**Comment by uli42** [comment]
Hmm, I have opened a discussion regarding that at tadpole's GitHub because
the readme does not mention anything about save states.

Goldstein ***@***.***> schrieb am Di., 3. Okt. 2023, 02:13:
