### ISSUE TITLE
fps counter available?

### ISSUE THREAD

**Issue by BarfingLemurs** [vonmillhausen/sf2000#13]
Hi, has there been a way towards getting an fps meter showing in games?
sorry I have no Discord.

**Comment by vonmillhausen** [comment]
Hi @BarfingLemurs! I'm not an expert on the software side of things (might be better to ask in the Multicore GitHub repo if you want something a bit more definitive: https://github.com/madcock/sf2000_multicore_cores), however as far as I know the answer is "no." Multicore is basically a modified version of the stock SF2000 OS, using the stock libretro interface, and that interface is incredibly bare-bones, and lacks many features of the full Retroarch libretro frontend you might be familiar with. One of the features lacking is the FPS reporting that Retroarch can do. Most cores (as far as I'm aware) also lack their own built-in FPS reporting mechanism.

The older hcrtos builds for the SF2000 _were_ full Retroarch builds, although given the platform they also lacked some features. I don't know specifically if they lacked FPS reporting, but I _do_ know their performance was different (usually worse) than the current Multicore builds, and so it wouldn't be an apples-to-apples comparison anyway.

I think there was some talk in the developer chat thread in Discord about potentially logging FPS stats to a logfile on the microSD card, but I'm not sure if anything ever came of that - if you don't want to set up a Discord account for yourself (which I'd strongly recommend) to ask the devs in the thread yourself, then your next best bet would be to ask over in the Multicore builds GitHub linked above.

Hope that helps!

**Comment by BarfingLemurs** [comment]
@vonmillhausen thank you for your time!
