### ISSUE TITLE
Information how to add ARCADE zip game

### ISSUE THREAD

**Issue by vovagorodok** [vonmillhausen/sf2000#14]
After adding ARCADE zip game using `tadpole`, game is visible in MAME menu, but stuck in infinite `loading..` screen. Checked with couple of games. Is here any instruction how to add new ARCADE to SF2000? Or will be nice to create some example for `calspeed` or another game

**Comment by vovagorodok** [comment]
Hmm, what does this files mean? : https://github.com/vonmillhausen/sf2000/tree/main/arcade

**Comment by vonmillhausen** [comment]
Hi @vovagorodok!

Arcade emulation (on any device, not just the SF2000) is _very_ different from emulation of any other system type (NES, SNES, Genesis, etc.); it's not sufficient to have a ZIP file for the game you want, the game must be supported by the specific emulator and version in question, and you must have the exact matching copy of the game that emulator and version expects - a different copy of the same game ZIP is likely not to work between emulators.

The files you linked to are the files linked from the Arcade section of my page (https://vonmillhausen.github.io/sf2000/#arcade) - I suggest you read it in full. One of the files includes an essentially complete list of all playable arcade games by the emulator and version available on the SF2000 - you will note `calspeed` is not included, and therefore will never work. DAT files to build a full working set for the SF2000 are included (again, if you're not sure what DAT files are or how to use them, I would suggest you look for a more general guide on arcade emulation - it's _very_ different, and outside the scope of my page to explain), along with a text file containing hints for source sets you might be able to use to build a working set using the DAT.

Good hunting!
