### ISSUE TITLE
Date of the firmware lacks the year

### ISSUE THREAD

**Issue by uli42** [vonmillhausen/sf2000#16]
As the SF2000 is a little older now the table with the firmware should be extended by release years /not just the month) for the firmwares to being able to easily spot if there's a recent update.

**Comment by vonmillhausen** [comment]
Thanks @uli42! I just added a note to say the days are relative to 2023 - I didn't want to go changing the semi-community-accepted names by adding years into them now, so I felt the note was the best compromise 👍
