### ISSUE TITLE
Possibly related controllors and consoles...

### ISSUE THREAD

**Issue by RamKromberg** [vonmillhausen/sf2000#17]
Not sure how noteworthy any of this is but a few odd aliexpress ads had me googling through some listings that suggest more controllers with additional buttons or a thumb stick as well as a compatible console:

[Wireless Gamepad with Rocker Gaming Controller for SNPRO/SF2000/SF900/SN-PLUS/SG800/Y2 SG/SG16/MD-MINI Dual Joysitck](https://www.aliexpress.com/item/1005006189096493.html) (aliexpress)

- Has a thumb stick.

[A Pair of Gamepad Only for SN/ / SN900 / SN16/ SG800 / Y2 SG / SG16](https://www.aliexpress.com/item/1005004206020032.html) (aliexpress)

- Has a couple of extra buttons.

[A Tiny $19 Retro Emulation Console WIth 10.000+ Games !... SN Plus / Max](https://www.youtube.com/watch?v=pi8tLrYPJYw) (youtube)

- A console that seems to be running about the same firmware.

The console seems to be the "tie-in" to the sf2000 but the first listing also suggests some mega drive esque "family" members?

Regards

**Comment by vonmillhausen** [comment]
Hi @RamKromberg! Yes indeedily - the SF2000 isn't the only device in the "family", it was just one of the first, and arguably the most popular. There are quite a few other "froggy" devices, which share most of the same internals - not only the SNES-shaped one you shared in your third link, but also various other handhelds (the GB300, the Q19, etc.) and also a bunch of different "HDMI sticks" that are designed to plug directly into a display. They all usually share very similar firmware, with some slight differences - the handhelds often use different display drivers, and so the firmware from one device can't usually be used on another without some modification. If you join the Retro Handhelds Discord server that's mentioned throughout my document, you'll find some discussions and threads about some of the other froggy devices in the `data_frog_sf2000` channel.

The "SN900" wireless controllers are indeed compatible with the SF2000; I mention the similarly named "SF900" controllers in my document, and in fact the page you linked to even has "SF900" in the description - they're all the same hardware, just with different branding. You'll find more discussion about those in the early days of the `data_frog_sf2000` channel mentioned above.

My own personal interest has always been with the original SF2000 design - I love the SNES inspiration, and the horizontal form-factor. As such, my own document is about that one specific iteration of the hardware. The Discord channel is a great place to go if you want to learn more about the other froggy devices, and if you have a specific interest in the vertical form-factor of the GB300 (another very popular froggy device), then nummacway's document is an absolute treasure-trove of information: https://nummacway.github.io/gb300/

Cheers!
