### ISSUE TITLE
Update Process Documentation

### ISSUE THREAD

**Issue by MmaxX09** [vonmillhausen/sf2000#2]
I'm loving the site so far, such an amazing collection of everything we know about a cheap little device that could become so much more. Altho I'm about confused about how to push updates and where to find them. They clearly are mentioned numerous times but I didnt find any info about how to update the actual device/ firmware on the sd card either on the github page or anywhere else on the web. I believe including this information would be amazing to help push innovation even further
Again thank you so much for taking all of the time :)

**Comment by vonmillhausen** [comment]
@MmaxX09 Thanks for the suggestion! I've just added a note to the firmware section with a link to Data Frog's YouTube video on the update process - their video's description contains a link to download the latest firmware 👍

**Comment by MmaxX09** [comment]
Amazing Thank you so so much!

Am Do., 18. Mai 2023 um 10:32 Uhr schrieb vonmillhausen <
***@***.***>:
