### ISSUE TITLE
NES/SNES

### ISSUE THREAD

**Issue by csrednicki** [vonmillhausen/sf2000#3]
Hi, great job. You are reffering to NES and SNES systems in readme, but in software they are called FC Family Computer and SFC Super Famicom. I think it should be mentioned somewhere that those are titles native only to Japan market and NES/SNES is USA/Europe naming.

**Comment by vonmillhausen** [comment]
Hi @csrednicki! While I take your point, I suspect very few Japanese-only folks are reading my page and wondering what "SNES" and "NES" are. I further suspect anyone who _is_ reading a page about the SF2000 is probably already sufficiently versed in the basics of retro emulation to have come across the terms before - I can't imagine anyone would come across the topic of retro emulation for the first time and have the SF2000 be the very first thing they experience on the topic.

Any folks out there who are confused about regional differences in terminology in relation to retro emulation need only search the web and instantly see what those devices are; so to keep my document a little lighter, I don't think I'm going to go into the level of specificity to point out regional differences in system naming. I hope that's OK! 👍
