### ISSUE TITLE
bisrv.asd 1.5v not working with Generic Image Tool 

### ISSUE THREAD

**Issue by Ludo-draw** [vonmillhausen/sf2000#4]
First, im very glad for this great tool, im enjoying so much to play with it

Since i updated my SF2000 to 1.5 version, the Generic Image Tool dont work anymore for the file "bisrv.asd"
If i try to extract the image, it gets a glitch image.
And if i try to convert an previous image it bricks the console to very glitchy

So, i will be very glad if you guys can fix it some day.

(sorry, my country language isnt english)

**Comment by vonmillhausen** [comment]
Hi there! The Generic Image Tool is not designed for use with the `bisrv.asd` BIOS file; its intended use is to work with the UI images stored in the `Resources` folder. The `bisrv.asd` BIOS file is mostly comprised of non-image data, and therefore is not something the Generic Image Tool was designed to process.

If you wish to modify the boot logo image stored in the `bisrv.asd` file, use the specific Boot Logo Changer tool instead: https://vonmillhausen.github.io/sf2000/tools/bootLogoChanger.htm

**Comment by Ludo-draw** [comment]
Solved. Thanks
