### ISSUE TITLE
is there a way to fast forward or increase the game's framerate?

### ISSUE THREAD

**Issue by shreyanshp** [vonmillhausen/sf2000#6]

**Comment by vonmillhausen** [comment]
Howdy! The issues section of this repo isn't really for asking general questions about the SF2000 - it's a place for reporting issues with the document (e.g., typos, factual errors, etc.).

If you have questions about the SF2000 that aren't answered in the document, the best place to ask would be in the Retro Handhelds Discord "data_frog_sf2000" channel: https://discord.com/channels/741895796315914271/1092831839955193987

**Comment by shreyanshp** [comment]
thank you so much!
