### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by xdpirate** [vonmillhausen/sf2000#7]
https://github.com/vonmillhausen/sf2000/blob/476417f9f19af733b41e7748a42ced5d1b17e760/README.md?plain=1#L74

The "Retro Handhelds" link is invalid for anyone not already in the specified Discord server (points to a channel), and is the first mention of said server present in the document. This might lead to confusion and I suggest changing the link to point to an invite link for the server instead.

**Comment by vonmillhausen** [comment]
Thank you kindly @xdpirate! I didn't know you couldn't deep-link into Discord server channels and stuff... that kinda sucks :(

I've gone ahead and updated all of the Discord links now 👍
