### ISSUE TITLE
Extra information about SNES performance

### ISSUE THREAD

**Issue by brunocmorais** [vonmillhausen/sf2000#8]
Hello, thanks for all information regarding the SF2000!

I found that some games run pretty differently on SNES according to the ROM's region, even after the second run. For instance, playing the NTSC version of F-Zero, it's expected to run at 60 fps. The background music plays fine at the right tempo, but the gameplay is far slower than usual.

On the other hand, using the PAL version, which runs at 50 fps, background music remains unaffected but the gameplay speed improves a lot, much closer to original. Besides, running PAL version is probably slightly less demanding than the NTSC one.

I don't know if this information is known or relevant at all, but I didn't find it on the docs, so I wanted to share this with the community, I think it can be useful to someone.

Thanks in advance!

**Comment by vonmillhausen** [comment]
Hi @brunocmorais! And you're very welcome, I'm glad you've found the page I've put together useful :)

That _is_ great information regarding SNES performance. The page I've put together doesn't really go into that level of detail (it's more sort of general information about the device itself)... however, the perfect place for the details you've found would be the community "DataFrog SF2000 Compatibility List", a spreadsheet where the community can report games that they've tested, and rate how well (or poorly) they perform on the SF2000. You can find it linked in [the "Tools and Links" section of my page](https://vonmillhausen.github.io/sf2000/#tools-and-links), and I'm sure your contributions will be most welcome. Just click the "Comment only" label in the toolbar at the top, then click "Request edit access" to request access to make edits from the document's owner (not me).

Hope that helps!
